# Generated by Django 5.1.5 on 2025-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlist_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='movie_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
